In [ ]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np


In [ ]:
oneDarray = np.array([1,2,3,4]) # create 1D array
print(oneDarray) # printing 1d array

[1 2 3 4]


In [ ]:
twoDarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 1D array
print(twoDarray) # printing 1d array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(oneDarray)

numpy.ndarray

In [ ]:
oneDarray.dtype

dtype('int64')

In [ ]:
oneDarray.size

4

In [ ]:
oneDarray.shape


(4,)

In [ ]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.zeros((3, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.empty((2,4))

array([[2.04945703e-316, 1.44295714e-312, 2.41907520e-312,
        2.05833592e-312],
       [9.76118064e-313, 2.22809558e-312, 2.14321575e-312,
        0.00000000e+000]])

In [ ]:
arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [ ]:
arr_reshape = np.reshape(arr, (3,4))
print(arr_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr_reshape.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])